name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t my-rails-app:$GITHUB_SHA .

    - name: Log in to Docker Hub (or other registry)
      run: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin

    - name: Push Docker image
      run: docker push iamxyz123/my-rails-app:$GITHUB_SHA


